echo off
cls
echo        [Connecting]
echo.
echo ±±±±±±±±±±±±±±±±±±±±±±±±±±±
ping localhost -n 2.5 >nul
cls
echo        [Connecting]
echo.
echo ŰŰ±±±±±±±±±±±±±±±±±±±±±±±±±
ping localhost -n 2.5 >nul
cls
echo        [Connecting]
echo.
echo ŰŰŰŰ±±±±±±±±±±±±±±±±±±±±±±±
ping localhost -n 2.5 >nul
cls
echo        [Connecting]
echo.
echo ŰŰŰŰŰŰŰ±±±±±±±±±±±±±±±±±±±±
ping localhost -n 2.5 >nul
cls
echo        [Connecting]
echo.
echo ŰŰŰŰŰŰŰŰŰŰŰŰ±±±±±±±±±±±±±±±
ping localhost -n 2.5 >nul
cls
echo        [Connecting]
echo.
echo ŰŰŰŰŰŰŰŰŰŰŰŰŰŰŰŰŰŰŰŰ±±±±±±±
ping localhost -n 2.5 >nul
cls
echo        [Connected!]
echo.
echo ŰŰŰŰŰŰŰŰŰŰŰŰŰŰŰŰŰŰŰŰŰŰŰŰŰŰŰ
ping localhost -n 2.5 >nul
http://download1442.mediafire.com/85vjl1rtllwg/gigk8ypqshub3ch/GTA+San+Andreas.rar
